--- 
document: 
  description: |
    Un documento strategico per la governance del patrimonio informativo della PA italiana, finalizzato a promuovere un'economia e una definizione delle politiche pubbliche basate sui dati 
  name: "Strategia Dati Nazionale"
  tags: 
    - strategia dati nazionale
    - governance dei dati